name: Build Binaries

on: [push, pull_request]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup CMake
      uses: lukka/get-cmake@v3
    - name: Setup Ninja
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install Ninja
      run: npm install -g ninja
    - name: Download ISPC
      run: |
        curl -Lo ispc.zip https://github.com/ispc/ispc/releases/download/v1.25.3/ispc-v1.25.3-windows.zip
        unzip ispc.zip -d ispc
    - name: Set up ISPC environment variable
      run: echo "ISPC_EXECUTABLE=$(pwd)/ispc/ispc.exe" >> $GITHUB_ENV
    - name: Run prepare_deps script
      run: .\prepare_deps.bat
    - name: Build with CMake
      run: cmake -GNinja -DCMAKE_BUILD_TYPE=Release && ninja

  build-macos:
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup CMake
      uses: lukka/get-cmake@v3
    - name: Setup Ninja
      run: brew install ninja
    - name: Download ISPC
      run: |
        curl -Lo ispc.tar.gz https://github.com/ispc/ispc/releases/download/v1.25.3/ispc-v1.25.3-macOS.universal.tar.gz
        tar -xzf ispc.tar.gz -C ispc
    - name: Set up ISPC environment variable
      run: echo "ISPC_EXECUTABLE=$(pwd)/ispc/ispc" >> $GITHUB_ENV
    - name: Run prepare_deps script
      run: ./prepare_deps.sh
    - name: Build with CMake
      run: cmake -GNinja -DCMAKE_BUILD_TYPE=Release && ninja

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup CMake
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake
    - name: Setup Ninja
      run: sudo apt-get install -y ninja-build
    - name: Download ISPC
      run: |
        curl -Lo ispc.tar.gz https://github.com/ispc/ispc/releases/download/v1.25.3/ispc-v1.25.3-linux.tar.gz
        tar -xzf ispc.tar.gz -C ispc
    - name: Set up ISPC environment variable
      run: echo "ISPC_EXECUTABLE=$(pwd)/ispc/ispc" >> $GITHUB_ENV
    - name: Run prepare_deps script
      run: ./prepare_deps.sh
    - name: Build with CMake
      run: cmake -GNinja -DCMAKE_BUILD_TYPE=Release && ninja
